export const products = [
    {
      productNumber: 1,
      name: "Diamond Ring",
      caraWt: 1.5,
      colorRange: "D",
      metalColor: "White Gold",
      netWEight: 3.0,
      goldPurity: "18K",
      price: 2000,
      category: "Rings",
      image: "path/to/diamond_ring.jpg",
      active: true
    },
    {
      productNumber: 2,
      name: "Sapphire Necklace",
      caraWt: 2.0,
      colorRange: "Blue",
      metalColor: "Yellow Gold",
      netWEight: 5.5,
      goldPurity: "14K",
      price: 3000,
      category: "Necklaces",
      image: "path/to/sapphire_necklace.jpg",
    },
    {
      productNumber: 3,
      name: "Emerald Earrings",
      caraWt: 1.8,
      colorRange: "Green",
      metalColor: "Rose Gold",
      netWEight: 4.0,
      goldPurity: "22K",
      price: 2500,
      category: "Earrings",
      image: "path/to/emerald_earrings.jpg",
    },
    {
      productNumber: 4,
      name: "Ruby Bracelet",
      caraWt: 1.0,
      colorRange: "Red",
      metalColor: "White Gold",
      netWEight: 2.5,
      goldPurity: "20K",
      price: 1800,
      category: "Bracelets",
      image: "path/to/ruby_bracelet.jpg",
    },
    {
      productNumber: 5,
      name: "Pearl Brooch",
      caraWt: 0.5,
      colorRange: "White",
      metalColor: "Yellow Gold",
      netWEight: 1.0,
      goldPurity: "14K",
      price: 1200,
      category: "Brooches",
      image: "path/to/pearl_brooch.jpg",
    },
    {
      productNumber: 6,
      name: "Topaz Ring",
      caraWt: 1.2,
      colorRange: "Sky Blue",
      metalColor: "White Gold",
      netWEight: 2.8,
      goldPurity: "18K",
      price: 1600,
      category: "Rings",
      image: "path/to/topaz_ring.jpg",
    },
    {
      productNumber: 7,
      name: "Amethyst Necklace",
      caraWt: 2.5,
      colorRange: "Purple",
      metalColor: "Rose Gold",
      netWEight: 4.5,
      goldPurity: "22K",
      price: 2800,
      category: "Necklaces",
      image: "path/to/amethyst_necklace.jpg",
    },
    {
      productNumber: 8,
      name: "Citrine Earrings",
      caraWt: 1.7,
      colorRange: "Yellow",
      metalColor: "Yellow Gold",
      netWEight: 3.5,
      goldPurity: "20K",
      price: 2000,
      category: "Earrings",
      image: "path/to/citrine_earrings.jpg",
    },
    {
      productNumber: 9,
      name: "Diamond Tennis Bracelet",
      caraWt: 3.0,
      colorRange: "D",
      metalColor: "White Gold",
      netWEight: 6.0,
      goldPurity: "18K",
      price: 3500,
      category: "Bracelets",
      image: "path/to/diamond_tennis_bracelet.jpg",
    },
    {
      productNumber: 10,
      name: "Sapphire and Diamond Pendant",
      caraWt: 1.3,
      colorRange: "Blue",
      metalColor: "Yellow Gold",
      netWEight: 2.0,
      goldPurity: "14K",
      price: 2200,
      category: "Pendants",
      image: "path/to/sapphire_diamond_pendant.jpg",
    },
  ];